<?php

add_action( 'vc_load_default_templates_action','my_custom_template_for_vc_myriad_misc' ); // Hook in
 
function my_custom_template_for_vc_myriad_misc() {
	
	$names = array("hero-with-text-block-and-boxes" => "Hero with text block and services",
				"services-boxes-with-bg-image-and-gradient-hover" => "Services Boxes with Bg Image and Gradient Hove",
				"testimonials-carousel-light-version" => "Testimonials Carousel Light Version",
				"hero-with-text-and-image-block" => "Hero with text and image block",
				"services-varied-colour-boxes" => "Services Varied Colour Boxes");
	
	$filters = array("hero-with-text-block-and-boxes" => "bra_hero bra_text",
				"services-boxes-with-bg-image-and-gradient-hover" => "bra_services bra_boxes bra_icons",
				"testimonials-carousel-light-version" => "bra_testimonials bra_sliders",
				"hero-with-text-and-image-block" => "bra_hero bra_text",
				"services-varied-colour-boxes" => "bra_serices bra_boxes");
	
	$brankic_template["hero-with-text-block-and-boxes"] = '[vc_row full_width="stretch_row" content_placement="middle" gap="10" row_bg_align="brankic_bg_bottom_left" row_bg_size="auto" row_bg_color_1="#06beb6" use_gradient_bg="true" row_gradient_direction="to bottom right" row_bg_color_2="#48b1bf" css=".vc_custom_1573824396148{padding-top: 12vh !important;padding-bottom: 12vh !important;}"][vc_column column_content_color="rgba(255,255,255,0.5)" offset="vc_col-md-5"][brankic_section_title title_color="#ffffff" h_weight="100" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="1px" small_title_color="#ffffff" title="App design agency based in Big Apple" small_title="Marketing and innovation" p_size_custom="13px"]

Our work is the presentation of our capabilities.

[/brankic_section_title][brankic_divider style="divider blank" margin="5px auto"][/brankic_divider][vc_column_text css_animation="none"]Stay positive and happy. Work hard and don\'t give up hope. Be open to criticism and keep learning. Surround yourself with happy, warm and genuine people.[/vc_column_text][brankic_divider style="divider blank"][/brankic_divider][brankic_button shape="radius" size="large" hover="dir-btt" text_color="#ffffff" text_hover_color="#ffffff" bg_color="#4b52aa" bg_color_2="#5266df" shadow_color="rgba(142,45,226,0.31)" hover_movement="up"][/vc_column][vc_column offset="vc_col-md-1"][/vc_column][vc_column column_bg_size="auto" offset="vc_col-md-6"][vc_row_inner content_placement="middle" gap="20" row_inner_bg_repeat="repeat" row_inner_bg_size="auto"][vc_column_inner offset="vc_col-md-6"][brankic_box box_bg_color="rgba(255,255,255,0.11)" hover="true" horizontal_align="text-align-center" vertical_align="vert-middle" box_border_radius="5px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.07)" type="linea" icon_size="2" icon_color="#ffffff" icon_color_hover="#06beb6" icon_border_shape="circle" icon_border_width="" icon_border_color="" icon_shape_padding="30" icon_bg_color="rgba(255,255,255,0.11)" icon_bg_color_hover="#ffffff" heading_size="h5" heading_color="#ffffff" content_color="rgba(255,255,255,0.5)" heading_and_text_style="i-row" box_height="" heading="High Security" icon_linea="icon icon-basic-anchor" box_url="#"]

Clients don\'t expect perfection, but honesty and transparency.

[/brankic_box][/vc_column_inner][vc_column_inner offset="vc_col-md-6"][brankic_box box_bg_color="rgba(255,255,255,0.11)" hover="true" horizontal_align="text-align-center" vertical_align="vert-middle" box_border_radius="5px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.07)" type="linea" icon_size="2" icon_color="#ffffff" icon_color_hover="#06beb6" icon_border_shape="circle" icon_border_width="" icon_border_color="" icon_shape_padding="30" icon_bg_color="rgba(255,255,255,0.11)" icon_bg_color_hover="#ffffff" heading_size="h5" heading_color="#ffffff" content_color="rgba(255,255,255,0.5)" heading_and_text_style="i-row" box_height="" heading="Modern Code" icon_linea="icon icon-basic-keyboard" box_url="#"]

Learning to write programs stretches your mind, and helps you think better.

[/brankic_box][brankic_divider style="divider blank" margin="10px auto"]

[/brankic_divider][brankic_box box_bg_color="rgba(255,255,255,0.11)" hover="true" horizontal_align="text-align-center" vertical_align="vert-middle" box_border_radius="5px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.07)" type="linea" icon_size="2" icon_color="#ffffff" icon_color_hover="#06beb6" icon_border_shape="circle" icon_border_width="" icon_border_color="" icon_shape_padding="30" icon_bg_color="rgba(255,255,255,0.11)" icon_bg_color_hover="#ffffff" heading_size="h5" heading_color="#ffffff" content_color="rgba(255,255,255,0.5)" heading_and_text_style="i-row" box_height="" row_gradient_direction="" heading="Creative Strategy" icon_linea="icon icon-basic-lightbulb" box_url="#"]

It takes alot of people to make a team. We are ready for greater challenges.

[/brankic_box][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]';

	$brankic_template["services-boxes-with-bg-image-and-gradient-hover"] = '[vc_row full_width="stretch_row_content" equal_height="yes" gap="15" row_bg_repeat="repeat" row_bg_size="auto" css=".vc_custom_1526329597550{padding-top: 150px !important;padding-right: 10% !important;padding-bottom: 150px !important;padding-left: 10% !important;background-color: #121212 !important;}"][vc_column][vc_row_inner row_inner_bg_repeat="repeat" css=".vc_custom_1570653539816{padding-bottom: 100px !important;}"][vc_column_inner width="1/4" offset="vc_hidden-sm vc_hidden-xs"][/vc_column_inner][vc_column_inner offset="vc_col-md-6"][brankic_section_title title_color="#ff9966" title_color_2="#ff5e62" h_tag="H3" h_size="40px" h_weight="normal" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="2px" small_title_color="rgba(255,255,255,0.71)" title="Creativity is the process of having original ideas that have value. It is a process, it\'s not random. " small_title="Ideas to explore" p_size_custom="11px"][/brankic_section_title][/vc_column_inner][vc_column_inner width="1/4" offset="vc_hidden-sm vc_hidden-xs"][/vc_column_inner][/vc_row_inner][vc_row_inner gap="15" row_inner_bg_repeat="repeat"][vc_column_inner width="1/2" offset="vc_col-md-3"][brankic_box box_bg_color="rgba(0,0,0,0.65)" hover="true" box_hover_bg_color="rgba(255,153,102,0.62)" box_hover_bg_color_2="#ff5e62" horizontal_align="text-align-left" vertical_align="vert-bottom" box_border_radius="4px" box_border_width="0px" type="material" icon_size="2" icon_color="#ffffff" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_size="h5" heading_color="#ffffff" content_color="rgba(255,255,255,0.71)" heading_and_text_style="i-row" box_height="height-50" border_shape="" border_width="" border_color="" height="" heading="Graphic Design" icon_material="vc-material vc-material-fingerprint" bg_image_extra="https://brankic1979demo.com/myriad28/wp-content/uploads/2019/10/70.jpg" box_url="#"]Sed ut perspiciatis unde omnis iste natus error sit accusantium unde
[/brankic_box][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-md-3"][brankic_box box_bg_color="rgba(0,0,0,0.7)" hover="true" box_hover_bg_color="rgba(255,153,102,0.62)" box_hover_bg_color_2="#ff5e62" horizontal_align="text-align-left" vertical_align="vert-bottom" box_border_radius="4px" box_border_width="0px" type="linea" icon_size="2" icon_color="#ffffff" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_size="h5" heading_color="#ffffff" content_color="rgba(255,255,255,0.71)" heading_and_text_style="i-row" box_height="height-50" border_shape="" border_width="" border_color="" height="" heading="Video Production" icon_linea="icon icon-basic-video" bg_image_extra="https://brankic1979demo.com/myriad28/wp-content/uploads/2019/10/23.jpg" box_url="#"]Voluptatem accusantium doloremque unde omnis iste unde omnis iste natus
[/brankic_box][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-md-3"][brankic_box box_bg_color="rgba(0,0,0,0.68)" hover="true" box_hover_bg_color="rgba(255,153,102,0.62)" box_hover_bg_color_2="#ff5e62" horizontal_align="text-align-left" vertical_align="vert-bottom" box_border_radius="4px" box_border_width="0px" type="linea" icon_size="2" icon_color="#ffffff" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_size="h5" heading_color="#ffffff" content_color="rgba(255,255,255,0.71)" heading_and_text_style="i-row" box_height="height-50" border_shape="" border_width="" border_color="" height="" heading="Branding" icon_linea="icon icon-software-pen" bg_image_extra="https://brankic1979demo.com/myriad28/wp-content/uploads/2019/10/69.jpg" box_url="#"]Lorem ipsum dolor sit amet, consectetuer adipiscing elit[/brankic_box][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-md-3"][brankic_box box_bg_color="rgba(0,0,0,0.77)" hover="true" box_hover_bg_color="rgba(255,153,102,0.62)" box_hover_bg_color_2="#ff5e62" horizontal_align="text-align-left" vertical_align="vert-bottom" box_border_radius="4px" box_border_width="0px" type="linea" icon_size="2" icon_color="#ffffff" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_size="h5" heading_color="#ffffff" content_color="rgba(255,255,255,0.69)" heading_and_text_style="i-row" box_height="height-50" border_shape="" border_width="" border_color="" height="" heading="App Design" icon_linea="icon icon-basic-tablet" bg_image_extra="https://brankic1979demo.com/myriad28/wp-content/uploads/2018/06/17.jpg" box_url="#"]Perspiciatis unde omnis iste natus error sit voluptatem unde natus[/brankic_box][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]';
	
	$brankic_template["testimonials-carousel-light-version"] = '[vc_row full_width="stretch_row_content" row_bg_repeat="repeat" row_bg_size="contain" row_bg_color_1="#ecf6ff" use_gradient_bg="true" row_gradient_direction="to bottom" row_bg_color_2="#ffffff" css=".vc_custom_1570652311221{padding-top: 12vh !important;padding-bottom: 12vh !important;}"][vc_column content_align="text-align-center" column_content_color="#45486e"][brankic_icon type="linecons" icon_size="2" bg_color="#45486e" border_shape="circle" border_width="" border_color="" icon_shape_padding="30" icon_color="#ffffff" icon_linecons="vc_li vc_li-like"][/brankic_icon][brankic_divider style="divider blank"][/brankic_divider][brankic_carousel shadow_color="" img_radius="true" img_radius_size="10px" testimonial_cat_slug="portfolio-testimonials" testimonial_post_id="none" testimonial_type="solid" text_color_testimonial="#45486e" text_color_name_occupation="#45486e" use_active_slide_diff_colors="true" active_background_color_testimonial="#ffffff" centered="true" emphasize_opacity="true" gap="60" shadow_color_active="rgba(0,0,0,0.11)"][/brankic_carousel][/vc_column][/vc_row]';
	
	$brankic_template["hero-with-text-and-image-block"] = '[vc_row full_width="stretch_row" full_height="yes" content_placement="middle" row_bg_align="brankic_bg_top" row_brankic_bg_image_extra="https://brankic1979demo.com/myriad28/wp-content/uploads/2019/10/82.jpg" css=".vc_custom_1570651946866{padding-top: 10vh !important;padding-bottom: 10vh !important;}"][vc_column column_content_color="rgba(255,255,255,0.5)" css=".vc_custom_1570651931692{background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_row_inner gap="50" row_inner_bg_repeat="repeat"][vc_column_inner offset="vc_col-md-6"][brankic_section_title title_color="#ffffff" p_size="custom" p_transform="uppercase" p_spacing="5px" small_title_color="#ffffff" title="Always deliver more than expected." small_title="Our main goal" p_size_custom="12px"][/brankic_section_title][brankic_divider style="divider blank" margin="10px auto"][/brankic_divider][vc_column_text]The modern artist… is working and expressing an inner world, expressing the energy, the motion, and other inner forces. And the only way to do that is to overcome our need for invulnerability. [/vc_column_text][brankic_divider style="divider blank" margin="20px auto"][/brankic_divider][brankic_button shape="radius" text_color="#ffffff" bg_color="#63d5ef"][/vc_column_inner][vc_column_inner offset="vc_col-md-6"][brankic_image shadow_color="rgba(0,0,0,0.25)" border_radius="9px" image_extra="https://brankic1979demo.com/myriad28/wp-content/uploads/2019/10/83.jpg"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]';
	
	$brankic_template["services-varied-colour-boxes"] = '[vc_row full_width="stretch_row" row_bg_color_1="#cfdef3" use_gradient_bg="true" row_gradient_direction="to bottom" row_bg_color_2="#e0eafc" row_bg_color_3="#ffffff" css=".vc_custom_1570651401796{padding-top: 12vh !important;padding-bottom: 12vh !important;}"][vc_column width="1/12" offset="vc_hidden-sm vc_hidden-xs"][/vc_column][vc_column column_content_color="#342c5d" offset="vc_col-md-10"][vc_row_inner row_inner_bg_repeat="repeat" css=".vc_custom_1570700406219{padding-bottom: 4vh !important;}"][vc_column_inner width="1/6" offset="vc_hidden-sm vc_hidden-xs"][/vc_column_inner][vc_column_inner content_align="text-align-center" offset="vc_col-md-8"][brankic_section_title h_transform="none" h_height="1.2" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="1px" title="App design agency based in Big Apple" small_title="Marketing and innovation" p_size_custom="13px"]Our work is the presentation
of our capabilities.[/brankic_section_title][vc_column_text css_animation="none"]Stay positive and happy. Work hard and don\'t give up hope. Be open to criticism and keep learning. Surround yourself with happy, warm and genuine people.[/vc_column_text][brankic_divider style="divider blank" margin="20px auto"][/brankic_divider][brankic_button shape="radius" hover="dir-btt" text_color="#2f2756" text_hover_color="#ffffff" bg_color="#ffffff" bg_hover_color="#2f2756" shadow_color="rgba(76,106,214,0.15)" hover_movement="up"][/vc_column_inner][vc_column_inner width="1/6" offset="vc_hidden-sm vc_hidden-xs"][/vc_column_inner][/vc_row_inner][vc_row_inner content_placement="middle" gap="20" row_inner_bg_repeat="repeat" css=".vc_custom_1570651321400{padding-top: 5vh !important;}"][vc_column_inner width="1/3" brankic_column_inner_height="height-25"][brankic_box box_bg_color="#fdad78" use_gradient_bg="true" box_gradient_direction="to bottom right" box_bg_color_2="#ffcc9f" horizontal_align="text-align-center" vertical_align="vert-middle" box_border_radius="5px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.03)" type="linea" icon_color="rgba(255,255,255,0.8)" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_size="h5" heading_color="#ffffff" content_color="#ffffff" heading_and_text_style="i-row" box_height="" icon_linea="icon icon-weather-newmoon" heading="Design"]What separates design from art is that design is meant to be... functional.[/brankic_box][/vc_column_inner][vc_column_inner width="1/3"][brankic_box box_bg_color="#6858b7" use_gradient_bg="true" box_gradient_direction="to bottom right" box_bg_color_2="#9988e3" horizontal_align="text-align-center" vertical_align="vert-middle" box_border_radius="5px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.03)" type="linea" icon_color="rgba(255,255,255,0.8)" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_size="h5" heading_color="#ffffff" content_color="#ffffff" heading_and_text_style="i-row" box_height="" icon_linea="icon icon-basic-keyboard" heading="Modern Code"]Learning to write programs stretches your mind, and helps you think better.[/brankic_box][brankic_divider style="divider blank" margin="10px auto"][/brankic_divider][brankic_box box_bg_color="#13b1a9" use_gradient_bg="true" box_gradient_direction="to bottom right" box_bg_color_2="#76e0da" horizontal_align="text-align-center" vertical_align="vert-middle" box_border_radius="5px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.03)" type="linea" icon_color="rgba(255,255,255,0.8)" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_size="h5" heading_color="#ffffff" content_color="#ffffff" heading_and_text_style="i-row" box_height="" icon_linea="icon icon-basic-lock" heading="High Security"]

Clients don\'t expect perfection, but they do expect honesty and transparency.

[/brankic_box][/vc_column_inner][vc_column_inner width="1/3"][brankic_box box_bg_color="#d56f8f" use_gradient_bg="true" box_gradient_direction="to bottom right" box_bg_color_2="#eda4bb" horizontal_align="text-align-center" vertical_align="vert-middle" box_border_radius="5px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.03)" type="linea" icon_color="rgba(255,255,255,0.8)" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_size="h5" heading_color="#ffffff" content_color="#ffffff" heading_and_text_style="i-row" box_height="" row_gradient_direction="" icon_linea="icon icon-software-layers2" heading="Creative Strategy"]

It takes alot of people to make a winning team. We are ready for greater challenges.

[/brankic_box][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/12" offset="vc_hidden-sm vc_hidden-xs"][/vc_column][/vc_row]';


foreach($names as $key => $value){
	$template_thumbs[$key] = "http://brankic1979demo.com/downloads/templates/" . $key . ".jpg"; 
}



foreach($brankic_template as $name => $template) {
	
	
	
	$data               = array();
    $data['name']       =  'Misc ' . $names[$name]; 
    $data['weight']     = 0; 
    $data['custom_class'] = 'brankic_template_for_vc_custom_template bra_misc ' . $filters[$name];
	$data['image_path'] = preg_replace( '/\s/', '%20', $template_thumbs[$name] ); 
	$data['content']    = 	$template;

    vc_add_default_templates( $data );
	
}
	

}