<?php

add_action( 'vc_load_default_templates_action','my_custom_template_for_vc_myriad13' ); // Hook in
 
function my_custom_template_for_vc_myriad13() {
	
	$names = array("m13-about-hero-with-asymmetric-image-collage" => "About - Hero with asymmetric image collage",
				"m13-contact" => "Contact page",
				"m13-home-brankic-super-slider" => "Home - Brankic super slider",
				"m13-home-banner" => "About us - Banner",
				"m13-home-fun-facts-counter-with-bg-image" => "Home - Fun facts counter with background image",
				"m13-home-offset-boxes" => "Home - Offset boxes",
				"m13-home-testimonials-with-bg-image" => "Home - Testimonials with background image",
				"m13-home-tour-info-details" => "Home - Tour info details");
				
	$filters = array("m13-about-hero-with-asymmetric-image-collage" => "bra_hero bra_image",
				"m13-contact" => "bra_contact",
				"m13-home-brankic-super-slider" => "bra_sliders bra_image bra_hero",
				"m13-home-banner" => "bra_hero",
				"m13-home-fun-facts-counter-with-bg-image" => "bra_counters",
				"m13-home-offset-boxes" => "bra_boxes bra_about bra_services",
				"m13-home-testimonials-with-bg-image" => "bra_testimonials bra_sliders",
				"m13-home-tour-info-details" => "bra_image bra_cta");
	
	$brankic_template["m13-about-hero-with-asymmetric-image-collage"] = '[vc_row full_width="stretch_row" content_placement="bottom" row_bg_align="brankic_bg_bottom" row_bg_color_1="#ffffff" use_gradient_bg="true" row_gradient_direction="to top" row_bg_color_2="rgba(255,255,255,0.01)" row_brankic_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/24-1.jpg"][vc_column brankic_column_height="height-60" content_align="text-align-center"][brankic_section_title title_color="rgba(17,67,87,0.1)" h_weight="900" h_transform="uppercase" h_spacing="custom" h_height="custom" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="#114357" h_spacing_custom="0.2em" small_title="Explore the world with us" p_size_custom="13px" h_height_custom="0.8"]Meet the team[/brankic_section_title][/vc_column][/vc_row][vc_row content_placement="middle" gap="20" css=".vc_custom_1560085903910{padding-bottom: 12vh !important;}"][vc_column width="1/4"][brankic_image shadow_color="rgba(0,0,0,0.05)" border_radius="3px" image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/06/41.jpg"][/vc_column][vc_column width="1/2"][vc_row_inner content_placement="bottom" gap="20" row_inner_bg_repeat="repeat"][vc_column_inner width="1/3"][brankic_image shadow_color="rgba(0,0,0,0.05)" border_radius="3px" image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/06/40.jpg"][/vc_column_inner][vc_column_inner width="2/3"][brankic_image shadow_color="rgba(0,0,0,0.05)" border_radius="3px" image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/06/11.jpg"][/vc_column_inner][/vc_row_inner][vc_row_inner content_placement="top" gap="20" row_inner_bg_repeat="repeat"][vc_column_inner width="7/12"][brankic_image shadow_color="rgba(0,0,0,0.05)" border_radius="3px" image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/06/42.jpg"][/vc_column_inner][vc_column_inner width="5/12"][brankic_image shadow_color="rgba(0,0,0,0.05)" border_radius="3px" image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/09/1-1.jpg"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/4"][brankic_image shadow_color="rgba(0,0,0,0.05)" border_radius="3px" image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/06/39.jpg"][/vc_column][/vc_row]';
	
	$brankic_template["m13-contact"] = '[vc_row full_width="stretch_row" row_bg_color_1="#e5d4b9" change_header_colors="true"][vc_column content_align="text-align-center" css=".vc_custom_1555876325392{padding-top: 5vh !important;}"][brankic_section_title title_color="rgba(0,0,0,0.11)" h_weight="900" h_transform="uppercase" h_spacing="custom" h_height="custom" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="rgba(0,0,0,0.26)" h_spacing_custom="0.2em" small_title="Let\'s travel together" p_size_custom="13px" h_height_custom="0.8"]Drop us a line[/brankic_section_title][/vc_column][/vc_row][vc_row full_width="stretch_row" content_placement="bottom" row_bg_align="brankic_bg_bottom_right" row_bg_size="contain" row_bg_color_1="#e5d4b9" change_header_colors="true" css=".vc_custom_1555876266469{padding-bottom: 130px !important;}"][vc_column width="5/6" column_content_color="#ffffff" css=".vc_custom_1554848457487{margin-bottom: 150px !important;padding-right: 60px !important;}" offset="vc_col-md-6"][vc_column_text]</p>
<h5>Contact us and let\'s make magic together. To send us a message or just to say hello, please complete the form or contact us via details listed below.</h5>
<p>[/vc_column_text][brankic_divider align="left" style="divider blank"][/brankic_divider][vc_column_text highlight_background_color_1="rgba(255,255,255,0.14)"]</p>
<h5><strong>Visit Us</strong></h5>
<p>Hallesches Ufer 23,<br />
10963 Berlin, Germany[/vc_column_text][brankic_divider width="width-10" color="rgba(255,255,255,0.3)" align="left" border_width="4"][/brankic_divider][vc_column_text]</p>
<h5><strong>Give Us a Call</strong></h5>
<p>+12 10963 - 578[/vc_column_text][brankic_divider width="width-10" color="rgba(255,255,255,0.3)" align="left" border_width="4"][/brankic_divider][vc_column_text]</p>
<h5><strong>Say Hello</strong></h5>
<p><span style="color: #ffffff;"><a style="color: #ffffff;" href="#">myriad.theme@brankic.net</a></span>[/vc_column_text][/vc_column][vc_column shadow_color="rgba(0,0,0,0.1)" column_bg_color_1="#ffffff" css=".vc_custom_1554848444441{padding-top: 50px !important;padding-right: 80px !important;padding-bottom: 50px !important;padding-left: 80px !important;border-radius: 5px !important;}" offset="vc_col-md-6"][brankic_contact_form_7 cf_7_id="8769" color="#114357" border_color="rgba(17,67,87,0.1)"][/vc_column][/vc_row][vc_row full_width="stretch_row_content" top_row_svg_mask_shape="slope" top_row_svg_mask_height="200px" top_row_svg_mask_fill_color="#e5d4b9" css=".vc_custom_1549047258274{margin-top: -300px !important;}"][vc_column column_bg_color_1="#dd3333"][vc_column_text][wpgmza id="1"][/vc_column_text][/vc_column][/vc_row]';

	$brankic_template["m13-home-brankic-super-slider"] = '[vc_row full_width="stretch_row_content" change_header_colors="true"][vc_column][brankic_super_slider_wrapper slider_height="height-100" navigation_vertical_align="none" border_radius="" autoheight="true"][brankic_super_slide bg_repeat="no-repeat" slide_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/08/43.jpg"][vc_row_inner row_inner_bg_repeat="repeat"][vc_column_inner offset="vc_col-md-4"][brankic_section_title title_color="#ffffff" h_size="custom" h_weight="900" h_transform="uppercase" h_spacing="custom" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="rgba(255,255,255,0.43)" title="App design agency that run on coffee." small_title="Create your own" h_size_custom="7vw" p_size_custom="13px" h_spacing_custom="0.3em"]<span class="google_web_font_2">Path</span>[/brankic_section_title][/vc_column_inner][vc_column_inner width="1/3" offset="vc_hidden-sm vc_hidden-xs"][/vc_column_inner][vc_column_inner column_inner_content_color="rgba(255,255,255,0.43)" css=".vc_custom_1569686203640{padding-top: 55px !important;}" offset="vc_col-md-4"][vc_column_text]
<h4><span class="w-500 google_web_font_3">Exploring is an innate part of being human. We\'re all explorers when we\'re born.</span></h4>
 

<small class="">Unfortunately, it seems to get drummed out of many of us as we get older, but it\'s there, I think, in all of us. And for me that moment of discovery is just so thrilling, on any level, that I think anybody that\'s experienced it is pretty quickly addicted to it.</small>[/vc_column_text][brankic_divider style="divider blank"][/brankic_divider][brankic_button button_text="Destinations" size="large" text_color="#ffffff" text_hover_color="#114357" bg_hover_color="#ffffff" border_color="rgba(255,255,255,0.21)" shadow_color="rgba(0,0,0,0.21)"][/vc_column_inner][/vc_row_inner][/brankic_super_slide][brankic_super_slide bg_repeat="repeat" slide_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/08/44.jpg"][vc_row_inner row_inner_bg_repeat="repeat"][vc_column_inner offset="vc_col-md-6"][brankic_section_title title_color="#ffffff" h_size="custom" h_weight="900" h_transform="uppercase" h_spacing="custom" h_height="1.2" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="rgba(255,255,255,0.43)" title="App design agency that run on coffee." small_title="Experience other" h_size_custom="7vw" p_size_custom="13px" h_spacing_custom="0.3em"]<span class="google_web_font_2">Cult
ures</span>[/brankic_section_title][brankic_divider style="divider blank" margin="10px auto"][/brankic_divider][brankic_button button_text="Explore more" size="large" text_color="#114357" text_hover_color="#ffffff" bg_color="#ffffff" bg_hover_color="#fc7f73" shadow_color="rgba(0,0,0,0.21)"][/vc_column_inner][vc_column_inner width="1/2"][/vc_column_inner][/vc_row_inner][/brankic_super_slide][brankic_super_slide bg_repeat="no-repeat" content_horizontal_align="left" content_vertical_align="bottom" slide_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/08/46.jpg"][vc_row_inner equal_height="yes" content_placement="bottom" row_inner_bg_repeat="repeat"][vc_column_inner offset="vc_col-md-8"][brankic_section_title title_color="#ffffff" h_size="custom" h_weight="900" h_transform="uppercase" h_spacing="custom" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="rgba(255,255,255,0.43)" title="App design agency that run on coffee." small_title="Create your own" h_size_custom="7vw" p_size_custom="13px" h_spacing_custom="0.3em"]<span class="google_web_font_2">Stories</span>[/brankic_section_title][/vc_column_inner][vc_column_inner width="1/3" content_align="text-align-right" content_align_tablet="tablet-text-align-left" column_inner_content_color="#ffffff" css=".vc_custom_1566902321756{padding-bottom: 6vh !important;}"][vc_column_text]
<h5><span class="w-500">Exploring is an innate part of being human. We\'re all explorers when we\'re born.</span></h5>
[/vc_column_text][brankic_divider style="divider blank" margin="10px auto"][/brankic_divider][brankic_button button_text="Explore more" size="large" text_color="#ffffff" bg_color="#114357" bg_hover_color="#fc7f73"][/vc_column_inner][/vc_row_inner][/brankic_super_slide][brankic_super_slide bg_align="brankic_bg_right" bg_repeat="no-repeat" slide_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/08/45.jpg"][vc_row_inner][vc_column_inner width="1/2"][/vc_column_inner][vc_column_inner width="1/2" centered_tablet="true" content_align="text-align-right" content_align_tablet="tablet-text-align-left"][brankic_section_title title_color="#ffffff" h_size="custom" h_weight="900" h_transform="uppercase" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="rgba(255,255,255,0.43)" title="App design agency that run on coffee." small_title="Explore the" h_size_custom="7vw" p_size_custom="13px"]<span class="google_web_font_2">Nature</span>[/brankic_section_title][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/3"][/vc_column_inner][vc_column_inner width="1/3" content_align_tablet="tablet-text-align-left"][/vc_column_inner][vc_column_inner width="1/2" centered_tablet="true" content_align="text-align-right" content_align_tablet="tablet-text-align-left" offset="vc_col-md-4"][vc_column_text]
<h5><span class="w-500">Exploring is an innate part of being human. We\'re all explorers when we\'re born.</span></h5>
[/vc_column_text][brankic_divider style="divider blank" margin="10px auto"][/brankic_divider][brankic_button button_text="Explore more" size="large" text_color="#ffffff" bg_color="#fc7f73" bg_hover_color="#114357" shadow_color="rgba(0,0,0,0.21)"][/vc_column_inner][/vc_row_inner][/brankic_super_slide][brankic_super_slide bg_align="brankic_bg_bottom" bg_repeat="no-repeat" slide_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/09/47.jpg"][vc_row_inner content_placement="middle" row_inner_bg_repeat="repeat"][vc_column_inner centered_tablet="true" content_align_tablet="tablet-text-align-center" column_inner_content_color="#ffffff" offset="vc_col-md-6" css=".vc_custom_1570043732320{padding-top: 5vh !important;padding-bottom: 5vh !important;}"][brankic_section_title title_color="#fc7f73" h_size="custom" h_weight="900" h_transform="uppercase" h_spacing="custom" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="rgba(255,255,255,0.43)" title="App design agency that run on coffee." small_title="Meet the" h_size_custom="7vw" p_size_custom="13px" h_spacing_custom=".2em"]<span class="google_web_font_2">People</span>[/brankic_section_title][vc_column_text]
<h5><span class="w-500 google_web_font_3">The deepest principle in human nature
is the craving to be appreciated. And for me that
moment of discovery is just so thrilling</span></h5>
[/vc_column_text][brankic_divider style="divider blank" margin="20px auto"][/brankic_divider][brankic_button button_text="Explore more" text_color="#114357" text_hover_color="#ffffff" bg_color="#ffffff" bg_hover_color="#114357" shadow_color="rgba(0,0,0,0.21)"][/vc_column_inner][vc_column_inner offset="vc_col-md-6"][brankic_collage shadow_color="rgba(0,0,0,0.49)" outset="10" thumb_sizes_1="brankic-original-1024" border_radius_1="5px" thumb_sizes_2="brankic-original-1024" border_radius_2="5px" thumb_sizes_3="brankic-original-1024" border_radius_3="5px" image_extra_1="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/06/11.jpg" image_extra_2="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/09/48.jpg" image_extra_3="https://brankic1979demo.com/myriad13/wp-content/uploads/2019/09/49.jpg"][/vc_column_inner][/vc_row_inner][/brankic_super_slide][/brankic_super_slider_wrapper][/vc_column][/vc_row]';
	
	$brankic_template["m13-home-banner"] = '[vc_row full_width="stretch_row" content_placement="middle" row_bg_align="brankic_bg_bottom" row_bg_size="auto" row_bg_color_1="#ffffff" use_gradient_bg="true" row_gradient_direction="to bottom" row_bg_color_2="rgba(255,255,255,0.01)" css=".vc_custom_1554844814826{padding-bottom: 15vh !important;}" row_brankic_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/23-1.jpg"][vc_column content_align="text-align-center" css=".vc_custom_1540326687897{padding-bottom: 80px !important;}"][brankic_section_title title_color="#114357" h_weight="900" h_transform="uppercase" h_spacing="custom" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="rgba(17,67,87,0.5)" small_title="Wanderlust" p_size_custom="13px" h_spacing_custom="0.2em"]Let’s Be<br />
Adventurers[/brankic_section_title][brankic_divider style="divider blank" margin="25px auto"][/brankic_divider][vc_column_text css=".vc_custom_1540326742495{padding-bottom: 50px !important;}"]Man cannot discover new oceans unless he has the courage to lose sight of the shore.[/vc_column_text][brankic_button shape="radius" button_text="Find out more" size="large" text_color="#ffffff" bg_color="#fc7f73" bg_hover_color="#114357" shadow_color="rgba(0,0,0,0.16)"][/vc_column][/vc_row]';
	
	$brankic_template["m13-home-fun-facts-counter-with-bg-image"] = '[vc_row full_width="stretch_row" gap="80" row_bg_color_1="#ffffff" use_gradient_bg="true" row_gradient_direction="to top" row_bg_color_2="rgba(255,255,255,0.43)" row_bg_color_3="rgba(255,255,255,0.01)" css=".vc_custom_1540197316746{padding-bottom: 20vh !important;}" row_brankic_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/8-1.jpg"][vc_column][vc_row_inner][vc_column_inner][brankic_section_title title_color="rgba(17,67,87,0.1)" h_weight="900" h_transform="uppercase" h_spacing="custom" h_spacing_custom="0.2em"]<span class="google_web_font_2">Fun facts</span>[/brankic_section_title][/vc_column_inner][/vc_row_inner][vc_row_inner row_inner_bg_repeat="repeat" css=".vc_custom_1540063804539{padding-bottom: 70px !important;}"][vc_column_inner offset="vc_col-md-6"][brankic_divider style="divider blank" margin="20px auto"][/brankic_divider][vc_column_text highlight_background_color_1="#3f51b5"]</p>
<h4>A positive attitude causes a chain reaction of positive thoughts</h4>
<p>[/vc_column_text][vc_column_text css=".vc_custom_1540210068659{padding-top: 15px !important;}"]If you have a positive attitude and constantly strive to give your best effort, eventually you will overcome your immediate problems and find you are ready for greater challenges.[/vc_column_text][/vc_column_inner][vc_column_inner width="1/2"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/2" offset="vc_col-md-3"][brankic_counter direction="column" caption_color="" counter_color="#fc7f73" counter_size="large" caption="Community Members" to="33"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-md-3"][brankic_counter direction="column" caption_color="" counter_color="#fc7f73" counter_size="large" caption="Miles Covered" to="971"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-md-3"][brankic_counter direction="column" caption_color="" counter_color="#fc7f73" counter_size="large" caption="Cups of Coffee" to="64"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-md-3"][brankic_counter direction="column" caption_color="" counter_color="#fc7f73" counter_size="large" caption="Finished Projects" to="72"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]';
	
	$brankic_template["m13-home-offset-boxes"] = '[vc_row full_width="stretch_row" content_placement="middle" row_bg_color_1="#ffffff" use_gradient_bg="true" row_gradient_direction="to bottom" row_bg_color_2="rgba(255,255,255,0.2)" row_bg_color_3="rgba(255,255,255,0.01)" css=".vc_custom_1554844950634{padding-top: 15vh !important;padding-bottom: 35vh !important;}" row_brankic_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/7-1.jpg"][vc_column width="1/6" css=".vc_custom_1529061495620{margin-top: -150px !important;}"][/vc_column][vc_column width="2/3" content_align="text-align-center"][brankic_section_title title_color="#fc7f73" h_weight="900" h_transform="uppercase" h_spacing="custom" h_spacing_custom="0.2em"]<span class="google_web_font_2">Discover</span>[/brankic_section_title][brankic_divider style="divider blank" margin="15px auto"][/brankic_divider][vc_row_inner][vc_column_inner width="1/6"][/vc_column_inner][vc_column_inner width="2/3" column_inner_content_color="rgba(0,0,0,0.5)"][vc_column_text]</p>
<h5><span class="google_web_font_1">Exploring is an innate part of being human. We\'re all explorers when we\'re born. Unfortunately, it seems to get drummed out of many of us as we get older, but it\'s there, I think, in all of us. And for me that moment of discovery is just so thrilling, on any level, that I think anybody that\'s experienced it is pretty quickly addicted to it.</span></h5>
<p>[/vc_column_text][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/6"][/vc_column][/vc_row][vc_row equal_height="yes" gap="20" row_bg_repeat="repeat" row_bg_size="auto" css=".vc_custom_1554845084537{margin-top: -20vh !important;padding-bottom: 15vh !important;}"][vc_column width="1/2" offset="vc_col-md-3"][brankic_box box_bg_color="rgba(0,0,0,0.39)" use_gradient_bg="true" box_gradient_direction="to top" box_bg_color_2="rgba(0,0,0,0.01)" zoom="true" horizontal_align="text-align-left" vertical_align="vert-bottom" box_border_radius="7px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.11)" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" content_color="#ffffff" heading_and_text_style="i-column" box_height="height-40" bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/4-1-1.jpg" box_url="#"]<strong>01.</strong></p>
<h4>Paris</h4>
<p>[/brankic_box][/vc_column][vc_column width="1/2" offset="vc_col-md-3"][brankic_box box_bg_color="rgba(0,0,0,0.38)" use_gradient_bg="true" box_gradient_direction="to top" box_bg_color_2="rgba(0,0,0,0.01)" zoom="true" horizontal_align="text-align-left" vertical_align="vert-bottom" box_border_radius="7px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.11)" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" content_color="#ffffff" heading_and_text_style="i-column" box_height="height-50" bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/5-3-1.jpg" box_url="#"]<strong>02.</strong></p>
<h4>Cappadocia</h4>
<p>[/brankic_box][/vc_column][vc_column width="1/2" offset="vc_col-md-3"][brankic_box box_bg_color="rgba(0,0,0,0.38)" use_gradient_bg="true" box_gradient_direction="to top" box_bg_color_2="rgba(0,0,0,0.01)" zoom="true" horizontal_align="text-align-left" vertical_align="vert-bottom" box_border_radius="7px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.11)" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" content_color="#ffffff" heading_and_text_style="i-column" box_height="height-50" bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/3-1-1.jpg" box_url="#"]<strong>03.</strong></p>
<h4>Toronto</h4>
<p>[/brankic_box][/vc_column][vc_column width="1/2" offset="vc_col-md-3"][brankic_box box_bg_color="rgba(0,0,0,0.38)" use_gradient_bg="true" box_gradient_direction="to top" box_bg_color_2="rgba(0,0,0,0.01)" zoom="true" horizontal_align="text-align-left" vertical_align="vert-bottom" box_border_radius="7px" box_border_width="0px" box_shadow_color="rgba(0,0,0,0.11)" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" content_color="#ffffff" heading_and_text_style="i-column" box_height="height-50" bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/2-2-1.jpg" box_url="#"]<strong>04.</strong></p>
<h4>Venice</h4>
<p>[/brankic_box][/vc_column][/vc_row]';
	
	$brankic_template["m13-home-testimonials-with-bg-image"] = '[vc_row css=".vc_custom_1540205877344{padding-top: 15vh !important;}"][vc_column content_align="text-align-center"][brankic_section_title title_color="rgba(17,67,87,0.1)" h_weight="900" h_transform="uppercase" h_spacing="custom" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="#114357" h_spacing_custom="0.2em" small_title="True stories " p_size_custom="13px"]<span class="google_web_font_2">Testimonials</span>[/brankic_section_title][/vc_column][/vc_row][vc_row full_width="stretch_row" row_bg_align="brankic_bg_bottom" css=".vc_custom_1540210156554{padding-top: 50px !important;padding-bottom: 30vh !important;}" row_brankic_bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/11-1.jpg"][vc_column width="1/4"][/vc_column][vc_column offset="vc_col-md-6"][brankic_carousel title_color="" testimonial_post_id="none" avatar_position_default="avatar-bottom" slides_per_view="1" gap=""][/brankic_carousel][/vc_column][vc_column width="1/4"][/vc_column][/vc_row]';
	
	$brankic_template["m13-home-tour-info-details"] = '[vc_row content_placement="bottom" css=".vc_custom_1540210861600{padding-top: 100px !important;padding-bottom: 40px !important;}"][vc_column][brankic_section_title title_color="rgba(17,67,87,0.1)" h_weight="900" h_transform="uppercase" h_spacing="custom" p_size="custom" p_weight="700" p_transform="uppercase" p_spacing="3px" small_title_color="#114357" h_spacing_custom="0.2em" small_title="Top Destination" p_size_custom="13px"]<span class="google_web_font_2">Toronto</span>[/brankic_section_title][/vc_column][/vc_row][vc_row gap="60" row_bg_color_1="#ffffff"][vc_column offset="vc_col-md-4"][vc_row_inner equal_height="yes" content_placement="middle" row_inner_bg_repeat="repeat"][vc_column_inner width="1/2" brankic_column_inner_height="height-20"][brankic_box zoom="true" thumb_sizes="3x4_s" horizontal_align="text-align-left" vertical_align="vert-top" box_border_radius="5px" box_border_width="0px" type="linea" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_and_text_style="i-column" box_height="height-20" bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/15-1.jpg" box_url="#"][/brankic_box][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1540210561868{padding-top: 10px !important;padding-bottom: 10px !important;padding-left: 30px !important;}"][vc_column_text]<small class="uppercase"><strong>01. What to see?<br />
</strong></small>[/vc_column_text][vc_column_text]The Gooderham Building, a.k.a. Flatiron Building[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][vc_column offset="vc_col-md-4"][vc_row_inner equal_height="yes" content_placement="middle" row_inner_bg_repeat="repeat"][vc_column_inner width="1/2" brankic_column_inner_height="height-20"][brankic_box zoom="true" thumb_sizes="4x3_s" horizontal_align="text-align-left" vertical_align="vert-top" box_border_radius="5px" box_border_width="0px" type="linea" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_and_text_style="i-column" box_height="height-20" bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/14-1.jpg" box_url="#"][/brankic_box][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1540210575316{padding-top: 10px !important;padding-bottom: 10px !important;padding-left: 30px !important;}"][vc_column_text]<small class="uppercase"><strong>02. What to do?<br />
</strong></small>[/vc_column_text][vc_column_text]Niagara Falls day, Distillery district walking tour[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][vc_column offset="vc_col-md-4"][vc_row_inner equal_height="yes" content_placement="middle" row_inner_bg_repeat="repeat"][vc_column_inner width="1/2" brankic_column_inner_height="height-20"][brankic_box zoom="true" thumb_sizes="4x3_s" horizontal_align="text-align-left" vertical_align="vert-top" box_border_radius="5px" box_border_width="0px" type="linea" icon_border_shape="" icon_border_width="" icon_border_color="" icon_shape_padding="0" icon_bg_color="" heading_and_text_style="i-column" box_height="height-20" bg_image_extra="https://brankic1979demo.com/myriad13/wp-content/uploads/2018/10/16-1.jpg" box_url="#"][/brankic_box][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1540210587563{padding-top: 10px !important;padding-bottom: 10px !important;padding-left: 30px !important;}"][vc_column_text]<small class="uppercase"><strong>03. Where to eat?<br />
</strong></small>[/vc_column_text][vc_column_text]Rodney\'s Oyster House, 17 Steakhouse and Bar[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1554844068858{padding-top: 5vh !important;padding-bottom: 5vh !important;}"][vc_column width="1/3"][brankic_button shape="button-circle arrow-link" text_color="#114357" arrow_color="#114357" arrow_hover_color="#ffffff" bg_color="rgba(17,67,87,0.1)" bg_hover_color="#114357"][/vc_column][vc_column width="1/3"][/vc_column][vc_column width="1/3"][/vc_column][/vc_row]';
	

foreach($names as $key => $value){
	$template_thumbs[$key] = "http://brankic1979demo.com/downloads/templates/" . $key . ".jpg"; 
}



foreach($brankic_template as $name => $template) {
	
	
	
	$data               = array();
    $data['name']       =  'Myriad13 ' . $names[$name]; 
    $data['weight']     = 0; 
    $data['custom_class'] = 'brankic_template_for_vc_custom_template bra_myriad13 ' . $filters[$name] ;
	$data['image_path'] = preg_replace( '/\s/', '%20', $template_thumbs[$name] ); 
	$data['content']    = 	$template;

    vc_add_default_templates( $data );
	
}
	

}